version: 2.1
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: "Setup virtual env"
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-notion
            source /usr/local/share/virtualenvs/tap-notion/bin/activate
            pip install -U "pip==22.2.2" "setuptools==65.3.0"
            pip install .[dev]
      - run:
          name: "JSON Validator"
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_notion/schemas/*.json
      - run:
          name: "pylint"
          command: |
            source /usr/local/share/virtualenvs/tap-notion/bin/activate
            pip install pylint
            pylint tap_notion -d C,R,W
      - run:
          name: "Unit Tests"
          command: |
            source /usr/local/share/virtualenvs/tap-notion/bin/activate
            pip install nose coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_notion --cover-html-dir=htmlcov tests/unittests
            coverage html
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      # - run:
      #     name: "Integration Tests"
      #     command: |
      #       source /usr/local/share/virtualenvs/tap-tester/bin/activate
      #       uv pip install --upgrade awscli
      #       aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
      #       source dev_env.sh
      #       run-test --tap=tap-notion tests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user